### PR TITLE
Change ConsumerConfig AckPolicy default to Explicit

### PR DESCRIPTION
**Pull request by hanlong-chen-1047**
Currently the no-args constructor for `ConsumerConfig` does not set the `AckPolicy` for the consumer, which defaults it to `None`. This is confusing given that the NATS docs state that the default `AckPolicy` is `Explicit`:
https://docs.nats.io/nats-concepts/jetstream/consumers#ackpolicy

This has led to unexpected behaviors since we had expected this to be set to `Explicit` by default for all consumers.

This PR changes the no-args `ConsumerConfig` constructor to set the `AckPolicy` to `Explicit`, to be the same as the constructor with a durable name.

### CODE REVIEW

**Comment by mtmk** [comment]
This sounds like a sensible thing to do actually ([potentially related discussions](https://github.com/nats-io/nats.net.v2/discussions?discussions_q=consumerconfig))

cc @robertmircea

**Comment by caleblloyd** [comment]
Should we consider changing the default value of the enum `ConsumerConfigAckPolicy` to `Explicit` instead of `None`?

**Comment by mtmk** [comment]
> Should we consider changing the default value of the enum `ConsumerConfigAckPolicy` to `Explicit` instead of `None`?

it might make more sense for other scenarios as well e.g.
```csharp
    AckPolicy = default,
```

**Comment by robertmircea** [comment]
Fine with me. I was setting it to Explicit every time

**Comment by mtmk** [comment]
looking at this closer enum:
```csharp
public enum ConsumerConfigAckPolicy
{
    Explicit = 0, // <--- hurts my eyes
    All = 1,
    None = 2,
}
```
...having `None = 0` is more conventional and it's aligned with how the server is working on the wire.

**Comment by hanlong-chen-1047** [comment]
> > Should we consider changing the default value of the enum `ConsumerConfigAckPolicy` to `Explicit` instead of `None`?
> 
> it might make more sense for other scenarios as well e.g.
> 
> ```cs
>     AckPolicy = default,
> ```
> 
> **Edit:** @hanlong-chen-1047 are you also happy with this suggestion? (I can make the change if you don't have time, not to worry)

yeah that'd be great

**Comment by caleblloyd** [comment]
There are some usages / examples now that no longer need to explicitly set the Ack policy to Explicit

https://github.com/nats-io/nats.net.v2/blob/f6c6419f34741dc9dabfbe400c4861d25901a579/tests/NATS.Client.JetStream.Tests/JetStreamTest.cs#L81

https://github.com/nats-io/nats.net.v2/blob/f6c6419f34741dc9dabfbe400c4861d25901a579/tests/NATS.Client.CheckNativeAot/Program.cs#L91

https://github.com/nats-io/nats.net.v2/blob/f6c6419f34741dc9dabfbe400c4861d25901a579/tests/NATS.Client.Core.MemoryTests/NatsConsumeTests.cs#L32

https://github.com/nats-io/nats.net.v2/blob/f6c6419f34741dc9dabfbe400c4861d25901a579/tests/NATS.Net.DocsExamples/JetStream/ManagingPage.cs#L73

https://github.com/nats-io/nats.net.v2/blob/f6c6419f34741dc9dabfbe400c4861d25901a579/src/NATS.Client.JetStream/Models/ConsumerConfig.cs#L32

**Review by caleblloyd — APPROVED** [review]
LGTM

**Pull request merged**
