### PR TITLE
Key/Value and Object Store compression

### PR DESCRIPTION
**Pull request by mtmk**
contributes to nats-io/nats-architecture-and-design#253

### CODE REVIEW

**Comment by caleblloyd** [comment]
Looks like Deno uses `Compression` with the actual Compression options in the config.  Which makes more sense if there will ultimately be multiple Compression options to choose from

**Comment by caleblloyd** [comment]
https://github.com/nats-io/nats.deno/pull/625/files

**Comment by mtmk** [comment]
> Looks like Deno uses `Compression` with the actual Compression options in the config. Which makes more sense if there will ultimately be multiple Compression options to choose from

I think there was a discussion about it and ADR says it should be bool also Go and Java using bool. Not sure why deno is different also rust looks the same as well. huh?!

**Comment by mtmk** [comment]
Turns out it should be bool.

**Comment by mtmk** [comment]
> What do the other Clients call the Config param? Or is there a matching Stream Config param name that we should align?

Go is using 'Compression' and 'IsCompressed'. [ADR is the same](https://github.com/nats-io/nats-architecture-and-design/pull/252/files#diff-c195b0afc458299fabf26f0d2fb05a9b6bc0db0475dad8885d020b199046c355R288).

**Review by caleblloyd — APPROVED** [review]
LGTM

**Pull request merged**
