### PR TITLE
Stream CreateConsumer renamed CreateOrUpdateConsumer

### PR DESCRIPTION
**Pull request by mtmk**

### CODE REVIEW

**Comment by caleblloyd** [comment]
Do Streams exhibit the same behavior?

**Comment by mtmk** [comment]
> Do Streams exhibit the same behavior?

Streams has a create() and an update() method.

Just tested create() make sure: Using create() is idempotent. It won't update if configuration is different with an error `stream name already in use with a different configuration` but it doesn't complain if it has the exact same configuration.

**Review by caleblloyd — APPROVED** [review]
LGTM

**Comment by caleblloyd** [comment]
> Just tested create() make sure: Using create() is idempotent. It won't update if configuration is different with an error `stream name already in use with a different configuration` but it doesn't complain if it has the exact same configuration.

I wonder if we should add a stream CreateOrUpdateAsync that does 2 calls - a Get, and conditionally a Create or Update after that.  Wonder if that is standard in other clients or not?

**Pull request merged**
